name: Notificacion DevOps

on:
  push:
    branches:
      - main

jobs:
  enviar_notificacion:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar mensaje a ntfy
        run: |
          curl -d "🚀 Nuevo push realizado en GitHub Actions" https://ntfy.sh/devops-itla
